// code by savir singh

// auto-generated by cpide
// the ide built for competitive programming

//================================================================
// Name        : ecoo21p3.cpp
// Author      : volcano
// Description : idk rn
//================================================================

#include <bits/stdc++.h>
using namespace std;

const int MM = 2e5 + 1;
int n, m, k, a, b, c, bestans[MM], val[MM];

int main() {
    ios::sync_with_stdio(false);cin.tie(nullptr);
    memset(bestans, -1, sizeof bestans);
    cin >> n >> m >> k;
    for (int i = 0; i < k; ++i) {
        cin >> a >> b >> c;
        if (c > val[b]) {
            bestans[b] = a;
            val[b] = c;
        }
    }
    for (int i = 1; i < n; ++i) {
        cout << bestans[i] << ' ';
    }
    cout << bestans[n] << endl;
}
