// code by savir singh
// https://dmoj.ca/problem/oly18novp1
// 100/100

// Olympiads Homework

// auto-generated by cpide
// the ide built for competitive programming

//================================================================
// Name        : oly18novp1.cpp
// Author      : volcano
// Description : weird task scheduling problem
//================================================================

#include <bits/stdc++.h>
using namespace std;
#define pb push_back
#define pii pair<int, int>

int n, tot = 0;
vector<pii> seg;

bool cuscom(pii a, pii b) {
    if (a.second == b.second) return a.second < b.second;
    return a.second < b.second;
}

int main() {
    ios::sync_with_stdio(false);cin.tie(nullptr);
    cin >> n;
    for (int i = 0; i < n; ++i) {
        int l, r; cin >> l >> r;
        seg.pb({l, r});
    }
    sort(seg.begin(), seg.end(), cuscom);
    int cur = seg[0].first;
    for (int i = 0 ; i < n; ++i) {
        if (seg[i].first >= cur) {
            tot++; cur = seg[i].second;
        }
    }
    cout << tot << endl;
}
